# Generated by Django 4.2.4 on 2023-12-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://luigispizzakenosha.com/wp-content/uploads/placeholder.png', max_length=500),
        ),
    ]
